### ISSUE TITLE
colorama module not found error message

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [grapheneX/grapheneX#89]
**Describe the bug**
When trying to install grapheneX on my second Linux PC (A Kodachi OS Netbook, in which the convontionnal installation method via python3 command works flawlessly), I wanted to redo a clean install of grapheneX on my main PC, which as i could remember, had issues with the colorama module.
(Before that, I was running it locally from the cloned repository like explained in the Readme.md)
Well, I still have this issue, being stuck with the `colorama module not found` error message.

**Log Messages**
```bash
pm at Velvet4Renaissance in ~
$ PIP uninstall colorama
WARNING: The directory '/home/pm/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Uninstalling colorama-0.4.1:
  Would remove:
    /usr/local/lib/python3.6/dist-packages/colorama-0.4.1.dist-info/*
    /usr/local/lib/python3.6/dist-packages/colorama/*
Proceed (y/n)? y
  Successfully uninstalled colorama-0.4.1
pm at Velvet4Renaissance in ~
$ PIP install grapheneX
WARNING: The directory '/home/pm/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/home/pm/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: grapheneX in /usr/local/lib/python3.6/dist-packages (1.1.1)
Requirement already satisfied: flask-socketio in /usr/local/lib/python3.6/dist-packages (from grapheneX) (4.2.1)
Requirement already satisfied: coloredlogs in /usr/local/lib/python3.6/dist-packages (from grapheneX) (10.0)
Collecting colorama (from grapheneX)
  Downloading https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Requirement already satisfied: pyinquirer in /usr/local/lib/python3.6/dist-packages (from grapheneX) (1.0.3)
Requirement already satisfied: terminaltables in /usr/local/lib/python3.6/dist-packages (from grapheneX) (3.1.0)
Requirement already satisfied: python-socketio>=4.3.0 in /usr/local/lib/python3.6/dist-packages (from flask-socketio->grapheneX) (4.3.1)
Requirement already satisfied: Flask>=0.9 in /usr/local/lib/python3.6/dist-packages (from flask-socketio->grapheneX) (1.1.1)
Requirement already satisfied: humanfriendly>=4.7 in /usr/local/lib/python3.6/dist-packages (from coloredlogs->grapheneX) (4.18)
Requirement already satisfied: Pygments>=2.2.0 in /usr/local/lib/python3.6/dist-packages (from pyinquirer->grapheneX) (2.4.2)
Requirement already satisfied: prompt-toolkit==1.0.14 in /usr/local/lib/python3.6/dist-packages (from pyinquirer->grapheneX) (1.0.14)
Requirement already satisfied: regex>=2016.11.21 in /usr/local/lib/python3.6/dist-packages (from pyinquirer->grapheneX) (2019.8.19)
Requirement already satisfied: python-engineio>=3.9.0 in /usr/local/lib/python3.6/dist-packages (from python-socketio>=4.3.0->flask-socketio->grapheneX) (3.9.3)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from python-socketio>=4.3.0->flask-socketio->grapheneX) (1.11.0)
Requirement already satisfied: Jinja2>=2.10.1 in /usr/local/lib/python3.6/dist-packages (from Flask>=0.9->flask-socketio->grapheneX) (2.10.1)
Requirement already satisfied: Werkzeug>=0.15 in /usr/local/lib/python3.6/dist-packages (from Flask>=0.9->flask-socketio->grapheneX) (0.15.5)
Requirement already satisfied: click>=5.1 in /usr/local/lib/python3.6/dist-packages (from Flask>=0.9->flask-socketio->grapheneX) (7.0)
Requirement already satisfied: itsdangerous>=0.24 in /usr/local/lib/python3.6/dist-packages (from Flask>=0.9->flask-socketio->grapheneX) (1.1.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/dist-packages (from prompt-toolkit==1.0.14->pyinquirer->grapheneX) (0.1.7)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib/python3/dist-packages (from Jinja2>=2.10.1->Flask>=0.9->flask-socketio->grapheneX) (1.0)
Installing collected packages: colorama
Successfully installed colorama-0.4.1
pm at Velvet4Renaissance in ~
$ grapheneX -w
colorama module not found.
```
(Note that the PIP command is just bash extension that allows capitalized command to be run as sudo, It can be found here https://github.com/jthistle/SUDO.)

**Expected behavior**
After installing the correct packages listed from `pip install grapheneX`, It should not have the following `colorama module not found` error message.

**Desktop (please complete the following information):**
```
         eeeeeeeeeeeeeeeee            pm@Velvet4Renaissance 
      eeeeeeeeeeeeeeeeeeeeeee         --------------------- 
    eeeee  eeeeeeeeeeee   eeeee       OS: elementary OS 5.0 Juno x86_64 
  eeee   eeeee       eee     eeee     Host: MS-7918 1.0 
 eeee   eeee          eee     eeee    Kernel: 5.2.0-9.1-liquorix-amd64 
eee    eee            eee       eee   Uptime: 3 hours, 10 mins 
eee   eee            eee        eee   Packages: 3547 
ee    eee           eeee       eeee   Shell: bash 4.4.20 
ee    eee         eeeee      eeeeee   Resolution: 3440x1440 
ee    eee       eeeee      eeeee ee   DE: Pantheon 
eee   eeee   eeeeee      eeeee  eee   WM: Mutter(Gala) 
eee    eeeeeeeeee     eeeeee    eee   Theme: Elementary-x [GTK3] 
 eeeeeeeeeeeeeeeeeeeeeeee    eeeee    Icons: La-Capitaine [GTK3] 
  eeeeeeee eeeeeeeeeeee      eeee     Terminal: io.elementary.t 
    eeeee                 eeeee       CPU: Intel i7-4790 (8) @ 4.000GHz 
      eeeeeee         eeeeeee         GPU: NVIDIA GeForce GTX 1060 6GB 
         eeeeeeeeeeeeeeeee            Memory: 9135MiB / 32111MiB 

```
**Additional context**

And yep, that the same PC/configuration has my other issues posted here. Most of the grapheneX hardening commands was already applied when trying to install properly grapheneX, but this issue was already happening before the hardening process.

**Comment by orhun** [comment]
Actually, it was a known problem for us which I thought that I fixed with 6155e961e954e423f6696554e65a909a93f9c6c1.
So I followed the same scenario, it's working for me:

![Screenshot from 2019-08-20 20-02-08](https://user-images.githubusercontent.com/24392180/63354170-a4c88600-c36c-11e9-900d-12436de65f0b.jpg)

Can you try to import colorama in Python interactive shell as following?
```
>>> from colorama import init, Fore, Style
>>> init()
```

**Comment by PoorPocketsMcNewHold** [comment]
The output of `from colorama import init, Fore, Style` is `from: can't read /var/mail/colorama`.
And, after checking, there indeed no colorama folder here (In fact, Just nothing in that mail folder)
Creating a folder does make the first command pass, without any output, and the second one works, but is waiting for an input.

**Comment by orhun** [comment]
Here what I can find about that issue: https://stackoverflow.com/questions/16069816/getting-python-error-from-cant-read-var-mail-bio
Did you run that command in the Python interactive shell? If so, I'll keep researching.

**Comment by PoorPocketsMcNewHold** [comment]
I’ve did. No results with it.
Tested explicitly with python3 as well as you can see, in case it was due to the wrong python version being used.
```bash
pm at Velvet4Renaissance in ~
$ python
Python 2.7.15+ (default, Nov 27 2018, 23:36:35) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from colorama import init, Fore, Style
>>> init()
>>> grapheneX
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'grapheneX' is not defined
>>> pip install grapheneX
  File "<stdin>", line 1
    pip install grapheneX
              ^
SyntaxError: invalid syntax
>>> 
pm at Velvet4Renaissance in ~
$ python3
Python 3.7.4 (default, Jul 12 2019, 20:57:46) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from colorama import init, Fore, Style
>>> init()
>>> grapheneX
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'grapheneX' is not defined
>>> pip install graphenex
  File "<stdin>", line 1
    pip install graphenex
              ^
SyntaxError: invalid syntax
>>> 
pm at Velvet4Renaissance in ~
$ pip install grapheneX
Requirement already satisfied: grapheneX in /usr/local/lib/python3.6/dist-packages (1.1.1)
Requirement already satisfied: colorama in /usr/local/lib/python3.6/dist-packages (from grapheneX) (0.4.1)
Requirement already satisfied: pyinquirer in /usr/local/lib/python3.6/dist-packages (from grapheneX) (1.0.3)
Requirement already satisfied: terminaltables in /usr/local/lib/python3.6/dist-packages (from grapheneX) (3.1.0)
Requirement already satisfied: flask-socketio in /usr/local/lib/python3.6/dist-packages (from grapheneX) (4.2.1)
Requirement already satisfied: coloredlogs in /usr/local/lib/python3.6/dist-packages (from grapheneX) (10.0)
Requirement already satisfied: prompt-toolkit==1.0.14 in /usr/local/lib/python3.6/dist-packages (from pyinquirer->grapheneX) (1.0.14)
Requirement already satisfied: regex>=2016.11.21 in /usr/local/lib/python3.6/dist-packages (from pyinquirer->grapheneX) (2019.8.19)
Requirement already satisfied: Pygments>=2.2.0 in /usr/local/lib/python3.6/dist-packages (from pyinquirer->grapheneX) (2.4.2)
Requirement already satisfied: python-socketio>=4.3.0 in /usr/local/lib/python3.6/dist-packages (from flask-socketio->grapheneX) (4.3.1)
Requirement already satisfied: Flask>=0.9 in /usr/local/lib/python3.6/dist-packages (from flask-socketio->grapheneX) (1.1.1)
Requirement already satisfied: humanfriendly>=4.7 in /usr/local/lib/python3.6/dist-packages (from coloredlogs->grapheneX) (4.18)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from prompt-toolkit==1.0.14->pyinquirer->grapheneX) (1.11.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/dist-packages (from prompt-toolkit==1.0.14->pyinquirer->grapheneX) (0.1.7)
Requirement already satisfied: python-engineio>=3.9.0 in /usr/local/lib/python3.6/dist-packages (from python-socketio>=4.3.0->flask-socketio->grapheneX) (3.9.3)
Requirement already satisfied: Jinja2>=2.10.1 in /usr/local/lib/python3.6/dist-packages (from Flask>=0.9->flask-socketio->grapheneX) (2.10.1)
Requirement already satisfied: itsdangerous>=0.24 in /usr/local/lib/python3.6/dist-packages (from Flask>=0.9->flask-socketio->grapheneX) (1.1.0)
Requirement already satisfied: Werkzeug>=0.15 in /usr/local/lib/python3.6/dist-packages (from Flask>=0.9->flask-socketio->grapheneX) (0.15.5)
Requirement already satisfied: click>=5.1 in /usr/local/lib/python3.6/dist-packages (from Flask>=0.9->flask-socketio->grapheneX) (7.0)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib/python3/dist-packages (from Jinja2>=2.10.1->Flask>=0.9->flask-socketio->grapheneX) (1.0)
pm at Velvet4Renaissance in ~
$ grapheneX
colorama module not found.
```

**Comment by orhun** [comment]
Alright, working on it.

**Comment by orhun** [comment]
I've removed the function that shows error message at https://github.com/keylo99/grapheneX/commit/a0bd2b5ffd4e1424ff01311514e07f42751d93e4
Maybe we can see what's the real problem with that change.
So, can you clone my fork repository and try to run grapheneX as I show below?
```
git clone https://github.com/keylo99/grapheneX/ && cd grapheneX
git checkout dev
python graphenex/__main__.py
```

**Comment by PoorPocketsMcNewHold** [comment]
GrapheneX works now perfectly by launching it, as explained (Except with the python part, which i’ve had to launch with python3 because it would default to python 2.7)
Here's the logs.
```bash
pm at Velvet4Renaissance in ~
$ cd grapheneX/
pm at Velvet4Renaissance in ~/grapheneX on master*
$ git pull
remote: Enumerating objects: 101, done.
remote: Counting objects: 100% (101/101), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 142 (delta 81), reused 93 (delta 76), pack-reused 41
Réception d'objets: 100% (142/142), 26.56 KiB | 22.00 KiB/s, fait.
Résolution des deltas: 100% (86/86), complété avec 12 objets locaux.
Depuis https://github.com/grapheneX/grapheneX
   0fc3930..545739b  master     -> origin/master
   72e5cfe..4a36d74  dev        -> origin/dev
 * [nouvelle étiquette] 1.1.2      -> 1.1.2
 * [nouvelle étiquette] 1.1.1      -> 1.1.1
Mise à jour 0fc3930..545739b
error: Vos modifications locales aux fichiers suivants seraient écrasées par la fusion :
	Pipfile
	Pipfile.lock
Veuillez valider ou remiser vos modifications avant la fusion.
Abandon
pm at Velvet4Renaissance in ~/grapheneX on master▼
$ RM -f -r Pipfile Pipfile.lock
Identified face as pm
pm at Velvet4Renaissance in ~/grapheneX on master▼
$ git pull
Mise à jour 0fc3930..545739b
Fast-forward
 .all-contributorsrc             | 18 ++++++++++++++++++
 .bumbversion.cfg                |  2 +-
 Pipfile                         |  1 +
 Pipfile.lock                    | 34 +++++++++++++---------------------
 README.md                       | 23 +++++++++++++++++++++++
 docker/Dockerfile               | 36 ++++++++++++++++++++++++++++++++++++
 graphenex/__init__.py           |  2 +-
 graphenex/core/utils/helpers.py |  2 +-
 graphenex/modules.json          | 67 ++++++++++++++++++++++++++++++-------------------------------------
 setup.py                        |  4 ++--
 10 files changed, 126 insertions(+), 63 deletions(-)
 create mode 100644 docker/Dockerfile
pm at Velvet4Renaissance in ~/grapheneX on master
$ git checkout dev
La branche 'dev' est paramétrée pour suivre la branche distante 'dev' depuis 'origin'.
Basculement sur la nouvelle branche 'dev'
pm at Velvet4Renaissance in ~/grapheneX on dev
$ python graphenex/__main__.py
  File "graphenex/__main__.py", line 15
    print(f"grapheneX v{__version__}")
                                    ^
SyntaxError: invalid syntax
pm at Velvet4Renaissance in ~/grapheneX on dev
$ python3 graphenex/__main__.py

                 +ho:`
           `:ohh. /dddy/.
        ./ydddddd/ -hddddho:          | grapheneX |
    `:ohdddddddddds``sddddds- :.      ~ Automated System Hardening Framework
    +ddddddddddddddh. /dds- /hdd      + Created for Linux & Windows.
    +dddddddddddddddd/ .. /hdddd      > https://github.com/grapheneX
    +ddddddddddddddddo``/hdddddd      - Copyright (C) 2019
    +ddddddddddddddo.`+ddddddddd
    `-/+oyhddddd+``+dddddddddddd
    :o+/-.` `-` .syddddddddddddd
    +dddddddyso+:-. `.-/+oyhdddd
     -+yddddddddddddhyso/:-` `-`
        `/sddddddddddddddy+-
            -+hddddddds:`
               `/sy+-
    
10:56:01 > graphenex.core.utils.helpers > INFO > grapheneX started.
10:56:01 > graphenex.core.utils.helpers > WARNING > Some functions won't work without root access, try running the grapheneX with sudo.
Welcome to the grapheneX interactive shell. Type "help" or "?" to list commands.
[gX]> 
```
So, as i´m french, The error message of the first git pull, says that it couldn´t update the following two Pipfile because one modification has been done to them apparently.
As i don´t recall doing this exact thing, I´ve just deleted them, and pulled the source from Github once again.
After that, the dev branch change passed without any issues, the message just stated that the dev branch was setup to follow the distant branch ´dev´ from ´origin´.

**Comment by orhun** [comment]
Okay then, I'll be creating a pull request for merging that change.
