### ISSUE TITLE
/usr/bin/su: Not accorded permission

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [grapheneX/grapheneX#95]
**Describe the bug**
I presume, using the Set_Permissions_Privilege_Escalation module in services, this caused to make myself unable to sudo or access root all together using my actual administrator account.

**Log Messages**
Executed all the modules, except those from the user category.

**Expected behavior**
Well, Should actually, still let me access root when i want it.
I presume, it just maked the sudoers file, not possible to be read by the system, and so, not being able to edit it or else.

**Desktop (please complete the following information):**
```bash
██████████████████  ████████   pm@Velvet4Renaissance 
██████████████████  ████████   --------------------- 
██████████████████  ████████   OS: Manjaro Linux x86_64 
██████████████████  ████████   Host: MS-7918 1.0 
████████            ████████   Kernel: 5.0.21-rt16-MANJARO 
████████  ████████  ████████   Uptime: 2 hours, 54 mins 
████████  ████████  ████████   Packages: 1769 (pacman) 
████████  ████████  ████████   Shell: bash 5.0.7 
████████  ████████  ████████   Resolution: 3440x1440 
████████  ████████  ████████   DE: KDE 
████████  ████████  ████████   WM: KWin 
████████  ████████  ████████   WM Theme: Blur-Glassy-v2 
████████  ████████  ████████   Theme: Cantalight [KDE], Breeze [GTK2/3] 
████████  ████████  ████████   Icons: Breeze_RCF [KDE], Breeze_RCF [GTK2/3] 
                               Terminal: guake 
                               CPU: Intel i7-4790 (8) @ 4.000GHz 
                               GPU: NVIDIA GeForce GTX 1060 6GB 
                               Memory: 5820MiB / 32112MiB 
```
(Yep, Same me again, but distro hopped, because Ubuntu LTS wasn´t really for me)

**Additional context**
I think i just need to reverse the file permissions on this file, so just launching the system in recovery should do the job, still wanted to precise this.
I´ve did used the web page interface for activating those. 
I don´t think this is caused directly by this, but it results into request errors.
```bash
[pm@Velvet4Renaissance ~]$ grapheneX -w

                 +ho:`
           `:ohh. /dddy/.
        ./ydddddd/ -hddddho:          | grapheneX |
    `:ohdddddddddds``sddddds- :.      ~ Automated System Hardening Framework
    +ddddddddddddddh. /dds- /hdd      + Created for Linux & Windows.
    +dddddddddddddddd/ .. /hdddd      > https://github.com/grapheneX
    +ddddddddddddddddo``/hdddddd      - Copyright (C) 2019
    +ddddddddddddddo.`+ddddddddd
    `-/+oyhddddd+``+dddddddddddd
    :o+/-.` `-` .syddddddddddddd
    +dddddddyso+:-. `.-/+oyhdddd
     -+yddddddddddddhyso/:-` `-`
        `/sddddddddddddddy+-
            -+hddddddds:`
               `/sy+-
    
20:58:44 > graphenex.core.utils.helpers > INFO > grapheneX started.
20:58:44 > graphenex.core.utils.helpers > WARNING > Some functions won't work without root access, try running the grapheneX with sudo.
20:58:44 > graphenex.core.web > INFO > Starting server: http://localhost:8080
20:58:44 > graphenex.core.web > INFO > Your access token: aBj7kYV_
 * Serving Flask app "graphenex.core.web" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Error on request:
Traceback (most recent call last):
  File "/home/pm/.local/pipx/venvs/graphenex/lib/python3.7/site-packages/werkzeug/serving.py", line 303, in run_wsgi
    execute(self.server.app)
  File "/home/pm/.local/pipx/venvs/graphenex/lib/python3.7/site-packages/werkzeug/serving.py", line 291, in execute
    application_iter = app(environ, start_response)
  File "/home/pm/.local/pipx/venvs/graphenex/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/pm/.local/pipx/venvs/graphenex/lib/python3.7/site-packages/flask_socketio/__init__.py", line 46, in __call__
    start_response)
  File "/home/pm/.local/pipx/venvs/graphenex/lib/python3.7/site-packages/engineio/middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/pm/.local/pipx/venvs/graphenex/lib/python3.7/site-packages/socketio/server.py", line 534, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/pm/.local/pipx/venvs/graphenex/lib/python3.7/site-packages/engineio/server.py", line 363, in handle_request
    socket = self._get_socket(sid)
  File "/home/pm/.local/pipx/venvs/graphenex/lib/python3.7/site-packages/engineio/server.py", line 551, in _get_socket
    raise KeyError('Session is disconnected')
KeyError: 'Session is disconnected'
```
EDIT : It´s Permission denied, Not the one i´ve used in the title, Sorry, but that´s difficult to do support talk, if you got your interface in a different language.

**Comment by orhun** [comment]
Okay, I'll check the aforementioned module and see if it's necessary or not. We were planning to release a new version soon so this will be fixed with that version probably. Thanks for the report.

**Comment by orhun** [comment]
We've concluded that it's not a necessary module. It'll be removed from the modules soon.

**Comment by orhun** [comment]
#97
